import { Sora } from "next/font/google";
import Navbar from "@/components/Navbar";
import AbsoluteImage from "@/components/AbsoluteImage";
import Header from "@/components/Header";

import "./globals.css";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div
          className={`page bg-site text-white bg-cover bg-no-repeat ${sora.variable}
    font-sora relative 
    `}
        >
          <Navbar />
          <Header />
          <AbsoluteImage
            imageSrc="/assets/kindpng_821901.png"
            width={110}
            height={110}
            className="top-[-45px] left-[-20px]"
          />
          <div className="bg-primary/40 h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
